PUT http://localhost:8080/api/v1/contact/2?name=Maria&phone=0126083269&email=maria123@gmail&dob=2000-01-04
Content-Type: JSON

###
GET http://localhost:8080/api/v1/contact/2

###
GET http://localhost:8080/api/v1/contact/searchByName?name=Mariam

###
DELETE http://localhost:8080/api/v1/contact/1





