PUT http://localhost:8080/api/v1/contact/1?name=Maria&email=maria123@gmail&dob=2000-01-04
Content-Type: JSON

###
GET http://localhost:8080/api/v1/contact/1

###
GET http://localhost:8080/api/v1/contact/searchByName?name=Mariam


